name: CI Workflow

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 src/ tests/

      - name: Run unit tests
        run: |
          pytest tests/unit --cov=src --cov-report=xml

      - name: Run integration tests
        run: |
          pytest tests/integration --cov=src --cov-report=xml

      - name: Run end-to-end tests
        run: |
          pytest tests/e2e --cov=src --cov-report=xml

      - name: Build Docker image
        run: |
          docker build -t galacticcoin:latest .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag galacticcoin:latest yourdockerhubusername/galacticcoin:latest
          docker push yourdockerhubusername/galacticcoin:latest

      - name: Notify on success
        if: success()
        run: |
          echo "CI build succeeded!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "CI build failed!"
